version: '3.8'

services:
  db:
    image: postgres:17.4-alpine
    container_name: warehouse-db
    restart: always
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: warehouse-redis
    restart: always
    ports:
      - "6379:6379"

  app:
    build:
      context: ..
      dockerfile: infra/Dockerfile
    container_name: warehouse-api
    restart: always
    depends_on:
      - db
    env_file:
      - ../.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
    ports:
      - "8000:8000"

volumes:
  postgres_data:
